version: '2'

services:
    nginx:
        restart: always
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - 8000:8000
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static_volume:/app/backend/server/static
    wsgiserver:
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        entrypoint: /app/docker/backend/wsgi-entrypoint.sh
        # stdin_open: true  # docker run -i
        # tty: true         # docker run -t
        volumes:
            - static_volume:/app/backend/server/static
        expose:
            - 8000
volumes:
    static_volume: {}
